server:
  port: 8080
  servlet:
    context-path: /api/v1
  undertow:
    accesslog:
      dir: ./logs/application/undertow_log
      enabled: true
      pattern: "%t %a %s \"%r\" %b (%D ms)"
      prefix: access-log.
      suffic: log
      rotate: true
  shutdown: graceful

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  sql:
    init:
      mode: always
      schema-locations: classpath:init_data/schema.sql
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: none
      jdbc:
        batch_size: 100
      order_inserts: true
      order_updates: true
      batch_versioned_data: true
    properties:
      hibernate:
#        show_sql: true
        format_sql : true

springdoc:
  swagger-ui:
    path: /apis
    doc-expansion: list
    tags-sorter: alpha
    operationSorter: method
    server:
      url: http://localhost:8080/api/v1
      description: local server
  show-actuator: false

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: "/health"
      exposure:
        include: health
  health:
    diskspace:
      enabled: false